baseURL = "https://rjb75.netlify.app/"
languageCode = "en-ca"
summaryLength = "10"
theme = "kross-hugo"
title = "Robert Brown | Personal Website"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[params]
address = ""
author = "Johnathan Smith"
copyright = "Copyright &copy; 2020 Robert Brown"
description = "This is meta description"
email = "hello@rjb75.com"
google_analytics_id = ""
home = "Home"
logo = "images/logo.png"
phone = "+880 2544 658 256"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://twitter.com/RobertJ_Brown"
icon = "ti-twitter-alt"
